# Generated by Django 5.0.1 on 2024-01-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_day', models.CharField(max_length=10)),
                ('end_day', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('job_id', models.CharField(max_length=5)),
                ('action', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
