# Generated by Django 5.0.1 on 2024-01-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workindia', '0002_jobs_contact_phno_alter_jobs_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
